In [1]:
import pandas as pd
import numpy as np

In [2]:
bt_df = pd.read_csv('Book_Tag.csv')
books = pd.read_csv('All_bools.csv')
bt_df.head()

C:\Users\Mahdi\AppData\Local\Temp\ipykernel_18128\2518371774.py:2: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('All_bools.csv')

   ids_book  ids_tags
0    121850       103
1    121850       134
2    121850       152
3    121850       207
4    121850       356

In [3]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49771 entries, 0 to 49770
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title_english   49258 non-null  object
 1   title_persian   49771 non-null  object
 2   book_bio        19346 non-null  object
 3   off_percent     37809 non-null  float64
 4   current_price   49771 non-null  float64
 5   rate            49771 non-null  float64
 6   status          49771 non-null  int64
 7   publisher_name  49771 non-null  object
 8   publisher_id    49771 non-null  int64
 9   ids_book        49771 non-null  int64
 10  shabak          49688 non-null  object
 11  pices           49647 non-null  object
 12  pages           49543 non-null  float64
 13  sunny_date      48547 non-null  float64
 14  monthy_date     26927 non-null  float64
 15  types           49642 non-null  object
 16  seriess         49343 non-null  float64
 17  reciving_time   37886 non-null  object
 18  descriptions    39085 non-null  object
 19  copies          707 non-null    float64
 20  type_copies     22 non-null     object
 21  language        1363 non-null   object
dtypes: float64(8), int64(3), object(11)
memory usage: 8.4+ MB

In [4]:
tags_df = pd.read_csv('Tags.csv')
tags_df.head()

           book_tags  ids_tags
0     ادبیات داستانی       103
1      ادبیات کلاسیک       134
2       ادبیات روسیه       152
3  جدید ترین کتاب ها       207
4       داستان کوتاه       356

In [5]:
id_love = tags_df[tags_df['book_tags'] == 'عاشقانه']['ids_tags']
id_love = id_love.to_list()[0]
print(id_love)

403

In [6]:
new_df = books.merge(bt_df, on=['ids_book'])
new_df

,title_english,title_persian,book_bio,off_percent,current_price,rate,status,publisher_name,publisher_id,ids_book,...,sunny_date,monthy_date,types,seriess,reciving_time,descriptions,copies,type_copies,language,ids_tags
0,Супруги Орловы,کتاب فروافتادگان,NaN,20.0,67600.0,3.71,1,ارس,2787,121850,...,1402.0,NaN,شومیز,1.0,8 مهر,NaN,NaN,NaN,NaN,103
1,Супруги Орловы,کتاب فروافتادگان,NaN,20.0,67600.0,3.71,1,ارس,2787,121850,...,1402.0,NaN,شومیز,1.0,8 مهر,NaN,NaN,NaN,NaN,134
2,Супруги Орловы,کتاب فروافتادگان,NaN,20.0,67600.0,3.71,1,ارس,2787,121850,...,1402.0,NaN,شومیز,1.0,8 مهر,NaN,NaN,NaN,NaN,152
3,Супруги Орловы,کتاب فروافتادگان,NaN,20.0,67600.0,3.71,1,ارس,2787,121850,...,1402.0,NaN,شومیز,1.0,8 مهر,NaN,NaN,NaN,NaN,207
4,Супруги Орловы,کتاب فروافتادگان,NaN,20.0,67600.0,3.71,1,ارس,2787,121850,...,1402.0,NaN,شومیز,1.0,8 مهر,NaN,NaN,NaN,NaN,356
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324646,Tech Savvy Parenting,کتاب فرزندپروری هوشمند در دنیای مدرن,NaN,NaN,70000.0,3.66,0,ارجمند,1362,72878,...,NaN,NaN,شومیز,1.0,NaN,ما نخستین نسل از پدر و مادرانی هستیم که فرزندا...,NaN,NaN,NaN,97
324647,Tech Savvy Parenting,کتاب فرزندپروری هوشمند در دنیای مدرن,NaN,NaN,70000.0,3.66,0,ارجمند,1362,72878,...,NaN,NaN,شومیز,1.0,NaN,ما نخستین نسل از پدر و مادرانی هستیم که فرزندا...,NaN,NaN,NaN,167
324648,Tech Savvy Parenting,کتاب فرزندپروری هوشمند در دنیای مدرن,NaN,NaN,70000.0,3.66,0,ارجمند,1362,72878,...,NaN,NaN,شومیز,1.0,NaN,ما نخستین نسل از پدر و مادرانی هستیم که فرزندا...,NaN,NaN,NaN,514
324649,Tech Savvy Parenting,کتاب فرزندپروری هوشمند در دنیای مدرن,NaN,NaN,70000.0,3.66,0,ارجمند,1362,72878,...,NaN,NaN,شومیز,1.0,NaN,ما نخستین نسل از پدر و مادرانی هستیم که فرزندا...,NaN,NaN,NaN,590
324650,Tech Savvy Parenting,کتاب فرزندپروری هوشمند در دنیای مدرن,NaN,NaN,70000.0,3.66,0,ارجمند,1362,72878,...,NaN,NaN,شومیز,1.0,NaN,ما نخستین نسل از پدر و مادرانی هستیم که فرزندا...,NaN,NaN,NaN,920

In [12]:
love_books = new_df[new_df['ids_tags'] == id_love]
love_books

,title_english,title_persian,book_bio,off_percent,current_price,rate,status,publisher_name,publisher_id,ids_book,...,sunny_date,monthy_date,types,seriess,reciving_time,descriptions,copies,type_copies,language,ids_tags
9410,Brooklyn,کتاب بروکلین,NaN,25.0,108750.0,3.66,1,مروارید,59,14171,...,1402.0,2009.0,شومیز,2.0,8 مهر,یکی از فراموش نشدنی ترین شخصیت های ادبیات معاص...,NaN,NaN,NaN,403
9418,Brooklyn,بروکلین,NaN,25.0,210000.0,3.59,1,افراز,10,14172,...,1397.0,2009.0,شومیز,1.0,9 مهر,یکی از فراموش نشدنی ترین شخصیت های ادبیات معاص...,NaN,NaN,NaN,403
11509,Graceling,کتاب هفت پادشاهی 1,(قریحه دار),25.0,191250.0,3.41,1,هوپا,1215,22507,...,1402.0,2008.0,شومیز,3.0,6 مهر,کاتسا خواهرزاده ی پادشاه، از شرایط فعلی زندگی ...,NaN,NaN,NaN,403
11721,Tara Road,کتاب جاده ی تارا,NaN,25.0,187500.0,3.75,1,کتابسرای تندیس,51,18819,...,1402.0,1998.0,شومیز,3.0,6 مهر,جاده تارا رمانی پرماجراست، ماجراهایی از جنس ام...,NaN,NaN,NaN,403
11884,War Brides,کتاب عروس های جنگ,NaN,25.0,180000.0,3.79,1,کتاب کوله پشتی,53,15223,...,1402.0,2006.0,شومیز,3.0,9 مهر,با تهدید برای گسترش جنگ از اروپا به انگلستان ،...,NaN,NaN,NaN,403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298669,101 Romantic Ideas,کتاب 101 ایده رمانتیک,NaN,NaN,25000.0,3.45,0,نشر علی,1781,41680,...,1395.0,2002.0,شومیز,5.0,NaN,کتاب شامل 101 روش جالب و خاطره انگیز برای جذاب...,NaN,NaN,NaN,403
308161,The Little Book of Love,کتاب کتاب کوچک عشق,NaN,NaN,2500.0,3.71,0,فراروان,1405,45943,...,1391.0,NaN,شومیز,5.0,NaN,شامل اشعار و جملات ادبیانه ی بزرگان شرق و غرب ...,NaN,NaN,NaN,403
309901,Boro Jelo Bough Nazan,کتاب برو جلو بوق نزن,NaN,15.0,34000.0,3.08,1,نشر نظر,1786,23624,...,1389.0,NaN,شومیز,1.0,10 مهر,مجموعة حاضر حاوی شعرهایی در قالب آزاد، با مضمو...,NaN,NaN,NaN,403
313097,What Color is Love?,کتاب دوست داشتن چه رنگی است,NaN,30.0,24500.0,3.87,1,قو,1578,53193,...,1382.0,1966.0,شومیز,2.0,9 مهر,"کتاب مصور و رنگی حاضر، متن کوتاهی است درباره ""...",NaN,NaN,NaN,403
314871,Emotional literacy and love,کتاب سواد عاطفی و عشق,NaN,20.0,100000.0,3.38,1,شباهنگ,1312,11896,...,1402.0,2018.0,شومیز,8.0,8 مهر,این کتاب سواد عاطفی و عشق بصورت گام به گام راه...,NaN,NaN,NaN,403

In [13]:
love_books = love_books.sort_values(['seriess', 'rate'], ascending= False).iloc[:20, ]
love_books

,title_english,title_persian,book_bio,off_percent,current_price,rate,status,publisher_name,publisher_id,ids_book,...,sunny_date,monthy_date,types,seriess,reciving_time,descriptions,copies,type_copies,language,ids_tags
38589,Looking for Alaska,کتاب در جست و جوی آلاسکا,NaN,15.0,160650.0,3.166667,1,میلکان,61,1582,...,1402.0,2005.0,شومیز,118.0,6 مهر,کتاب در جست و جوی آلاسکا، رمانی نوشته ی جان گر...,NaN,NaN,NaN,403
37776,Words in Deep Blue,کتاب واژه هایی در اعماق آبی دریا,NaN,20.0,168000.0,4.090000,1,کتاب کوله پشتی,53,14845,...,1402.0,2016.0,شومیز,92.0,8 مهر,یک داستان عاشقانه زیبا برای طرفداران جندی نلسو...,NaN,NaN,NaN,403
89451,Breakfast at Tiffany's,کتاب صبحانه در تیفانی,NaN,20.0,36000.0,3.890000,1,مروارید,59,1606,...,1401.0,1958.0,شومیز,85.0,6 مهر,کتاب صبحانه در تیفانی، رمانی نوشته ی ترومن کاپ...,NaN,NaN,NaN,403
89171,Sal-e- Balva,کتاب سال بلوا,NaN,15.0,148750.0,4.461538,1,ققنوس,48,4563,...,1402.0,NaN,شومیز,37.0,6 مهر,کتاب سال بلوا، رمانی نوشته ی عباس معروفی است ک...,NaN,NaN,NaN,403
88752,The Orange Girl,دختر پرتقالی,NaN,25.0,75000.0,3.300000,1,یوپا,1895,52859,...,1401.0,2003.0,شومیز,37.0,9 مهر,کتاب دختر پرتقالی، رمانی نوشته ی یوستین گوردر ...,NaN,NaN,NaN,403
84104,The Horse Dancer,اسب رقصان,NaN,NaN,48000.0,3.160000,0,فروزش,1293,3498,...,1397.0,2009.0,شومیز,36.0,NaN,کتاب اسب رقصان، رمانی نوشته ی جوجو مویز است که...,NaN,NaN,NaN,403
89181,Sal-e- Balva,سال بلوا (جیبی),NaN,NaN,75000.0,3.850000,0,ققنوس,48,1379,...,1401.0,NaN,شومیز,35.0,NaN,کتاب سال بلوا، رمانی نوشته ی عباس معروفی است ک...,NaN,NaN,NaN,403
192774,Soluk,سلوک (جلد سخت),NaN,NaN,72000.0,3.520000,0,نشر چشمه,33,5706,...,1401.0,NaN,زرکوب,35.0,NaN,کتاب سلوک، رمانی نوشته ی محمود دولت آبادی است ...,NaN,NaN,NaN,403
192756,Soluk,کتاب سلوک,NaN,20.0,96000.0,3.230000,1,نشر چشمه,33,16981,...,1401.0,NaN,شومیز,35.0,8 مهر,کتاب سلوک، رمانی نوشته ی محمود دولت آبادی است ...,NaN,NaN,NaN,403
33553,Yalda,کتاب یلدا,NaN,10.0,206910.0,3.200000,1,نیریز,1749,19775,...,1402.0,2007.0,شومیز,33.0,6 مهر,"""یلدا"" نام اثری است از ""م مودب پور"" که داستانی...",NaN,NaN,NaN,403
33253,They Both Die at the End,کتاب هر دو در نهایت می میرند,NaN,15.0,178500.0,3.958333,1,نشر نون,77,1995,...,1402.0,2017.0,شومیز,30.0,6 مهر,کتاب هر دو در نهایت می میرند، رمانی نوشته ی آد...,NaN,NaN,NaN,403
33073,Identity,کتاب هویت,NaN,15.0,59500.0,3.340000,1,قطره,87,1514,...,1402.0,1997.0,شومیز,27.0,6 مهر,کتاب هویت، رمانی نوشته ی میلان کوندرا است که ن...,NaN,NaN,NaN,403
88734,The Orange Girl,کتاب دختر پرتقالی,NaN,20.0,73600.0,4.142857,1,کتابسرای تندیس,51,2721,...,1401.0,2003.0,شومیز,26.0,6 مهر,کتاب دختر پرتقالی، رمانی نوشته ی یوستین گوردر ...,NaN,NaN,NaN,403
192765,Soluk,سلوک (جیبی),NaN,NaN,27000.0,3.620000,0,نشر چشمه,33,1431,...,1397.0,2003.0,جلد سخت,26.0,NaN,کتاب سلوک، رمانی نوشته ی محمود دولت آبادی است ...,NaN,NaN,NaN,403
32013,The Sorrows of Young Werther,رنج های ورتر جوان,NaN,NaN,100000.0,3.650000,0,ماهی,57,1369,...,1402.0,1774.0,شومیز,25.0,NaN,کتاب رنج های ورتر جوان، رمانی نوشته ی یوهان ول...,NaN,NaN,NaN,403
124689,Love Story,کتاب حکایت عاشقی,NaN,25.0,28125.0,3.920000,1,علمی,1404,20644,...,1400.0,2017.0,شومیز,23.0,6 مهر,کولی نوجوان پانزده ساله ی کنجکاوی است که به خو...,NaN,NaN,NaN,403
30610,Sense and Sensibility,کتاب عقل و احساس,NaN,10.0,198000.0,4.060000,1,نشر نی,66,1822,...,1402.0,1811.0,شومیز,22.0,6 مهر,کتاب عقل و احساس، رمانی نوشته ی جین آستین است ...,NaN,NaN,NaN,403
88743,The Orange Girl,دختر پرتقال,NaN,20.0,96000.0,3.580000,1,هرمس,69,31270,...,1402.0,2003.0,شومیز,21.0,6 مهر,کتاب دختر پرتقالی، رمانی نوشته ی یوستین گوردر ...,NaN,NaN,NaN,403
30131,By the River Piedra I Sat Down and Wept,کنار رودخانه پیدرا نشستم و گریه کردم,NaN,25.0,187500.0,3.570000,1,نشر ثالث,31,1386,...,1402.0,1994.0,شومیز,21.0,8 مهر,کتاب کنار رودخانه پیدرا نشستم و گریه کردم، رما...,NaN,NaN,NaN,403
29514,Poor Folk,کتاب بیچارگان,NaN,15.0,102000.0,3.333333,1,نشر نی,66,2372,...,1402.0,1846.0,شومیز,19.0,6 مهر,کتاب بیچارگان، رمانی نوشته ی فئودور داستایفسکی...,NaN,NaN,NaN,403

In [10]:
writers = pd.read_csv('Writer.csv')
bw_df = pd.read_csv('Book_writer.csv')

In [11]:
miane = bw_df.merge(writers, on= 'writer_id')
miane.head()

   ids_book  writer_id   writer_name
0    121850     3766.0  ماکسیم گورکی
1     22491     3766.0  ماکسیم گورکی
2      7843     3766.0  ماکسیم گورکی
3      2774     3766.0  ماکسیم گورکی
4     16131     3766.0  ماکسیم گورکی

In [14]:
fi_book = miane[miane['ids_book'].isin(love_books['ids_book'])]
# fi_book = miane[miane['ids_book'] in love_books['ids_book']]
fi_book

        ids_book  writer_id             writer_name
160         3498       62.0               جوجو مویز
797661      2372     1059.0       فئودور داستایفسکی
798222      1822      604.0               جین آستین
799912     20644    12000.0           کارن کینگزبری
801201     16981     2660.0        محمود دولت آبادی
801202      1431     2660.0        محمود دولت آبادی
801203      5706     2660.0        محمود دولت آبادی
803178      2721      423.0            یوستین گوردر
803179     31270      423.0            یوستین گوردر
803180     52859      423.0            یوستین گوردر
807402      1386      815.0           پائولو کوئیلو
810909      1606      667.0            ترومن کاپوتی
811125     19775     6014.0              م مودب پور
811584      1582      742.0                جان گرین
811602      1514      553.0            میلان کوندرا
812110      1369     1085.0  یوهان ولفگانگ فون گوته
812154      1995     3209.0             آدام سیلورا
812274      4563     2636.0             عباس معروفی
812275      1379     2636.0             عباس معروفی
812336     14845     8661.0                کت کرولی

Factors for choosing is Rate by books

In [16]:
names = fi_book.drop_duplicates('writer_name')
names = names['writer_name'].to_list()[:5]
print(names)

['جوجو مویز', 'فئودور داستایفسکی', 'جین آستین', 'کارن کینگزبری', 'محمود دولت آبادی']

In [19]:
id_his = tags_df[tags_df['book_tags'] == 'تاریخی']['ids_tags']
id_his = id_his.to_list()[0]
hist_books = new_df[new_df['ids_tags'] == id_his]
hist_books = hist_books.sort_values(['seriess', 'rate'], ascending= False).iloc[:20, ]
hist_books

,title_english,title_persian,book_bio,off_percent,current_price,rate,status,publisher_name,publisher_id,ids_book,...,sunny_date,monthy_date,types,seriess,reciving_time,descriptions,copies,type_copies,language,ids_tags
212317,Shahrnaz,کتاب شهرناز,داستان ادبی، اخلاقی و تاریخی,30.0,126000.0,3.45,1,امید فردا,1552,96954,...,1395.0,NaN,شومیز,903.0,6 مهر,به اعتقاد یحیی دولت آبادی کتاب شهرناز به حقیقت...,NaN,NaN,NaN,300
301939,The Art of Southeast Asia,کتاب هنر جنوب شرقی آسیا,NaN,20.0,44000.0,3.10,1,فرهنگستان هنر,1946,98841,...,1394.0,1967.0,شومیز,903.0,10 مهر,در این کتاب مصور، اطلاعات گسترده‌ای درباره‌ی چ...,NaN,NaN,NaN,300
310464,Artists for the Shah,کتاب نگارگری و حامیان صفوی,بررسی تحولات دوره گذار از مکتب قزوین به مکتب ا...,NaN,50000.0,3.10,0,فرهنگستان هنر,1946,98831,...,1389.0,1976.0,شومیز,902.0,NaN,"کتاب حاضر ترجمه‌ی کتاب ""Artist for the shah"" ت...",NaN,NaN,NaN,300
301942,Tabriz and qazvin- mashhad,کتاب مکتب نگارگری تبریز,NaN,20.0,44000.0,3.05,1,فرهنگستان هنر,1946,98854,...,1394.0,NaN,شومیز,902.0,6 مهر,کتاب « مکتب نگارگری تبریز» نوشته « یعقوب آژند»...,NaN,NaN,NaN,300
219489,Dokhtar Ghafghaz,کتاب دختر قفقاز,سرگذشت واقعی دختری نظامی از حزب دموکرات آذربای...,NaN,150000.0,3.51,0,امید فردا,1552,96949,...,1394.0,NaN,شومیز,901.0,NaN,کتاب حاضر، رمانی از سرگذشت واقعی دختر یک نظامی...,NaN,NaN,NaN,300
89411,Keshtiye pahlou gerefte,کتاب کشتی پهلو گرفته,NaN,20.0,35200.0,3.93,1,نیستان,1327,6587,...,1401.0,1989.0,شومیز,58.0,6 مهر,در میان معصومین از جایگاه رفیعی برخوردار است آ...,NaN,NaN,NaN,300
260461,The magisterial history of America,کتاب تاریخ مستطاب آمریکا,NaN,30.0,52500.0,3.98,1,شهید کاظمی,1977,97648,...,1401.0,NaN,شومیز,47.0,6 مهر,NaN,NaN,NaN,NaN,300
318888,History of Iranian literature,کتاب تاریخ ادبیات ایران - جلد 1,خ‍لاص‍ه ج‍ل‍د اول و دوم,30.0,161000.0,3.42,1,ققنوس,48,36568,...,1401.0,1953.0,شومیز,33.0,6 مهر,"""تاریخ ادبیات در ایران"" به تالیف دکتر ""ذبیح ال...",NaN,NaN,NaN,300
260402,Cyrus the great history reality,کتاب کورش کبیر حقیقت تاریخ,NaN,25.0,135000.0,3.57,1,ابریشمی,1528,75675,...,1401.0,NaN,شومیز,31.0,8 مهر,کتاب «کورش کبیر حقیقت تاریخ» نوشته‌ی «فرشاد اب...,NaN,NaN,NaN,300
260406,Cyrus the great history reality,کورش کبیر حقیقت تاریخ,NaN,NaN,180000.0,3.80,0,ابریشمی,1528,75729,...,1400.0,NaN,زرکوب,30.0,NaN,کتاب «کورش کبیر حقیقت تاریخ» نوشته‌ی «فرشاد اب...,NaN,NaN,NaN,300
124940,Edwardo,کتاب ادواردو,NaN,NaN,125000.0,3.20,0,عهد مانا,2009,69935,...,1400.0,2021.0,شومیز,29.0,NaN,"کتاب ""ادواردو"" نوشته بهزاد دانشگر است که توسط ...",NaN,NaN,NaN,300
246368,The Natural History Book,کتاب دایره المعارف مصور آفرینش,NaN,25.0,2250000.0,3.59,1,سایان,1468,34715,...,1402.0,2010.0,زرکوب,27.0,6 مهر,ما سیاره خود را با میلیون ها گونه گیاهی و جانو...,NaN,NaN,NaN,300
278962,Reza Khan,کتاب رضاخان از تولد تا سلطنت,(2جلدی),NaN,260000.0,3.10,0,دنیای کتاب,1119,30618,...,1399.0,2002.0,زرکوب,26.0,NaN,"""رضاخان از تولد تا سلطنت"" اثری است از دکتر ""رض...",2.0,NaN,NaN,300
278914,About Prehistoric Life,کتاب ماقبل تاریخ,چراهای شگفت انگیز,NaN,25000.0,3.96,0,محراب قلم,1326,48218,...,1399.0,2001.0,شومیز,22.0,NaN,از چه زمانی زندگی بر روی زمین آغاز شده است؟عصر...,NaN,NaN,NaN,300
291561,I Wonder Why Countries Fly Flags,کتاب مردم و کشورها,چراهای شگفت انگیز,NaN,25000.0,3.67,0,محراب قلم,1326,48209,...,1397.0,1995.0,شومیز,22.0,NaN,این کتاب از مجموعه ی چراهای شگفت انگیز به مطال...,NaN,NaN,NaN,300
246173,Iran,کتاب ایران باستان,چراهای شگفت انگیز (پ‍اس‍خ ب‍ه س‍وال ه‍ای ک‍ودک...,25.0,33750.0,3.40,1,محراب قلم,1326,116183,...,1402.0,NaN,شومیز,22.0,8 مهر,NaN,NaN,NaN,NaN,300
271227,Az Shar ta Shahr,کتاب از شار تا شهر,NaN,NaN,130000.0,3.48,0,دانشگاه تهران,1967,65257,...,1400.0,NaN,شومیز,19.0,NaN,دگردیسی مفهوم شهر، دگردیسی حافظه جمعی شهر است ...,NaN,NaN,NaN,300
259931,Ancient Greece,کتاب یونان باستان,چراهای شگفت انگیز,25.0,26250.0,3.98,1,محراب قلم,1326,27900,...,1401.0,1997.0,شومیز,16.0,9 مهر,در این مجموعه به سوال های اساسی کودکان و نوجوا...,NaN,NaN,NaN,300
315023,History Research methods,کتاب درآمدی بر روش پژوهش در تاریخ,NaN,10.0,198000.0,3.64,1,نشر نی,66,36183,...,1402.0,NaN,شومیز,16.0,10 مهر,کتاب «درآمدی بر روش پژوهش در تاریخ» نوشته «علی...,NaN,NaN,NaN,300
84635,Ghadir Dar Madaen,کتاب غدیر در مدائن,NaN,20.0,20000.0,3.32,1,شهید کاظمی,1977,55474,...,1401.0,NaN,شومیز,15.0,9 مهر,«غدیر در مدائن» اولین قدم در روایت داستانی غدی...,NaN,NaN,NaN,300

In [20]:
pub = hist_books.drop_duplicates('publisher_name')
pub = pub['publisher_name'].to_list()[:5]
print(pub)

['امید فردا', 'فرهنگستان هنر', 'نیستان', 'شهید کاظمی', 'ققنوس']