In [1]:
import pymysql
import numpy as np
import pandas as pd

In [28]:
data_frame = pd.read_csv('Final_Data.csv', low_memory=False)
data_frame.head()

,title_english,title_persian,book_bio,off_percent,current_price,rate,status,publisher_name,publisher_id,writer_name,...,descriptions,book_tags,ids_tags,english_dialogs,persian_dialogs,authors,pleasure_text,copies,type_copies,language
0,Супруги Орловы,کتاب فروافتادگان,NaN,20.0,67600.0,3.71,1,ارس,2787,['ماکسیم گورکی'],...,NaN,"['ادبیات داستانی', 'ادبیات کلاسیک', 'ادبیات رو...","[103, 134, 152, 207, 356]",[None],[None],[None],[None],NaN,NaN,NaN
1,Darbast Monirie,کتاب دربست منیریه,NaN,20.0,100000.0,3.43,1,دید,4450,['سالومه طهرانی'],...,NaN,"['ادبیات داستانی', 'ادبیات معاصر', 'جدید ترین ...","[103, 105, 207, 265, 356, 437]",[None],[None],[None],[None],NaN,NaN,NaN
2,Scarecrow,کتاب مترسک,NaN,NaN,69000.0,3.82,0,گیوا,2238,['فرزاد عزیزی کدخدایی'],...,جزء به جزء مترسک پیر، از کلاهش گرفته تا کت و ش...,"['ادبیات داستانی', 'داستان کوتاه', 'ادبیات ایر...","[103, 356, 437]",[None],[None],[None],[None],NaN,NaN,NaN
3,Please Join Us,کتاب لطفا به ما بپیوندید,NaN,NaN,280000.0,3.09,0,راه طلایی,2706,['کاترین مک کنزی'],...,لطفا به ما بپیوندید رمانی معمایی و هیجان انگیز...,"['ادبیات کانادا', 'داستان ماجرایی', 'داستان مع...","[19, 21, 24, 103, 105, 182, 801]",[None],[None],[None],[None],NaN,NaN,NaN
4,Shahnamek,کتاب شاهنامک,ویژه کودکان و نوجوانان,20.0,200000.0,3.98,1,پازینه,1534,['یاسر موحدفرد'],...,دخترهای گلم و پسرهای نازنینم شاهنامک میخواد خی...,"['ادبیات اقتباسی', 'ادبیات داستانی', 'ادبیات م...","[20, 103, 105, 114, 207, 265, 437, 539]",[None],[None],[None],[None],NaN,NaN,NaN

In [29]:
from ast import literal_eval

df_test = data_frame

In [30]:
df_test['book_tags'] = df_test['book_tags'].apply(literal_eval)
df_test['ids_tags'] = df_test['ids_tags'].apply(literal_eval)
df_test = df_test.explode(['book_tags', 'ids_tags'])
df_test = df_test[['book_tags', 'ids_tags']]
# df_test = df_test.explode('book_tags')
# df_test = df_test[['book_tags', 'ids_tags']]
df_test.head(20)

,title_english,title_persian,book_bio,off_percent,current_price,rate,status,publisher_name,publisher_id,writer_name,...,descriptions,book_tags,ids_tags,english_dialogs,persian_dialogs,authors,pleasure_text,copies,type_copies,language
0,Супруги Орловы,کتاب فروافتادگان,NaN,20.0,67600.0,3.71,1,ارس,2787,['ماکسیم گورکی'],...,NaN,ادبیات داستانی,103,[None],[None],[None],[None],NaN,NaN,NaN
0,Супруги Орловы,کتاب فروافتادگان,NaN,20.0,67600.0,3.71,1,ارس,2787,['ماکسیم گورکی'],...,NaN,ادبیات کلاسیک,134,[None],[None],[None],[None],NaN,NaN,NaN
0,Супруги Орловы,کتاب فروافتادگان,NaN,20.0,67600.0,3.71,1,ارس,2787,['ماکسیم گورکی'],...,NaN,ادبیات روسیه,152,[None],[None],[None],[None],NaN,NaN,NaN
0,Супруги Орловы,کتاب فروافتادگان,NaN,20.0,67600.0,3.71,1,ارس,2787,['ماکسیم گورکی'],...,NaN,جدید ترین کتاب ها,207,[None],[None],[None],[None],NaN,NaN,NaN
0,Супруги Орловы,کتاب فروافتادگان,NaN,20.0,67600.0,3.71,1,ارس,2787,['ماکسیم گورکی'],...,NaN,داستان کوتاه,356,[None],[None],[None],[None],NaN,NaN,NaN
1,Darbast Monirie,کتاب دربست منیریه,NaN,20.0,100000.0,3.43,1,دید,4450,['سالومه طهرانی'],...,NaN,ادبیات داستانی,103,[None],[None],[None],[None],NaN,NaN,NaN
1,Darbast Monirie,کتاب دربست منیریه,NaN,20.0,100000.0,3.43,1,دید,4450,['سالومه طهرانی'],...,NaN,ادبیات معاصر,105,[None],[None],[None],[None],NaN,NaN,NaN
1,Darbast Monirie,کتاب دربست منیریه,NaN,20.0,100000.0,3.43,1,دید,4450,['سالومه طهرانی'],...,NaN,جدید ترین کتاب ها,207,[None],[None],[None],[None],NaN,NaN,NaN
1,Darbast Monirie,کتاب دربست منیریه,NaN,20.0,100000.0,3.43,1,دید,4450,['سالومه طهرانی'],...,NaN,مجموعه داستان,265,[None],[None],[None],[None],NaN,NaN,NaN
1,Darbast Monirie,کتاب دربست منیریه,NaN,20.0,100000.0,3.43,1,دید,4450,['سالومه طهرانی'],...,NaN,داستان کوتاه,356,[None],[None],[None],[None],NaN,NaN,NaN
1,Darbast Monirie,کتاب دربست منیریه,NaN,20.0,100000.0,3.43,1,دید,4450,['سالومه طهرانی'],...,NaN,ادبیات ایران,437,[None],[None],[None],[None],NaN,NaN,NaN
2,Scarecrow,کتاب مترسک,NaN,NaN,69000.0,3.82,0,گیوا,2238,['فرزاد عزیزی کدخدایی'],...,جزء به جزء مترسک پیر، از کلاهش گرفته تا کت و ش...,ادبیات داستانی,103,[None],[None],[None],[None],NaN,NaN,NaN
2,Scarecrow,کتاب مترسک,NaN,NaN,69000.0,3.82,0,گیوا,2238,['فرزاد عزیزی کدخدایی'],...,جزء به جزء مترسک پیر، از کلاهش گرفته تا کت و ش...,داستان کوتاه,356,[None],[None],[None],[None],NaN,NaN,NaN
2,Scarecrow,کتاب مترسک,NaN,NaN,69000.0,3.82,0,گیوا,2238,['فرزاد عزیزی کدخدایی'],...,جزء به جزء مترسک پیر، از کلاهش گرفته تا کت و ش...,ادبیات ایران,437,[None],[None],[None],[None],NaN,NaN,NaN
3,Please Join Us,کتاب لطفا به ما بپیوندید,NaN,NaN,280000.0,3.09,0,راه طلایی,2706,['کاترین مک کنزی'],...,لطفا به ما بپیوندید رمانی معمایی و هیجان انگیز...,ادبیات کانادا,19,[None],[None],[None],[None],NaN,NaN,NaN
3,Please Join Us,کتاب لطفا به ما بپیوندید,NaN,NaN,280000.0,3.09,0,راه طلایی,2706,['کاترین مک کنزی'],...,لطفا به ما بپیوندید رمانی معمایی و هیجان انگیز...,داستان ماجرایی,21,[None],[None],[None],[None],NaN,NaN,NaN
3,Please Join Us,کتاب لطفا به ما بپیوندید,NaN,NaN,280000.0,3.09,0,راه طلایی,2706,['کاترین مک کنزی'],...,لطفا به ما بپیوندید رمانی معمایی و هیجان انگیز...,داستان معمایی,24,[None],[None],[None],[None],NaN,NaN,NaN
3,Please Join Us,کتاب لطفا به ما بپیوندید,NaN,NaN,280000.0,3.09,0,راه طلایی,2706,['کاترین مک کنزی'],...,لطفا به ما بپیوندید رمانی معمایی و هیجان انگیز...,ادبیات داستانی,103,[None],[None],[None],[None],NaN,NaN,NaN
3,Please Join Us,کتاب لطفا به ما بپیوندید,NaN,NaN,280000.0,3.09,0,راه طلایی,2706,['کاترین مک کنزی'],...,لطفا به ما بپیوندید رمانی معمایی و هیجان انگیز...,ادبیات معاصر,105,[None],[None],[None],[None],NaN,NaN,NaN
3,Please Join Us,کتاب لطفا به ما بپیوندید,NaN,NaN,280000.0,3.09,0,راه طلایی,2706,['کاترین مک کنزی'],...,لطفا به ما بپیوندید رمانی معمایی و هیجان انگیز...,رمان,182,[None],[None],[None],[None],NaN,NaN,NaN

In [31]:
df_test = df_test[['book_tags', 'ids_tags']]
df_test = df_test.drop_duplicates()
df_test.describe()

                                                book_tags  ids_tags
count                                                 948       948
unique                                                947       948
top     فهرست رمان های برگزیده درباره «بلوغ» و «دوران ...       103
freq                                                    2         1

In [ ]:
conn1 = pymysql.connect(host='localhost', user='root', passwd='1051047595Ma', db='schema_test')

# Insert desired columns from dataframe into movies table
with conn1:
    cursor = conn1.cursor()
    for index, row in df_test[['book_tags', 'ids_tags']].iterrows():
        sql = "INSERT INTO Tag (book_tags, ids_tags) VALUES (%s, %s)"
        cursor.execute(sql, tuple(row))
    conn1.commit()
    
print("DataFrame inserted into MySQL")